CPR-942: Automate Lit tests with extra verification options
Manually squash single file, as git says CONFLICT (content): Merge conflict in .github/workflows/compiler-integration-tests.yml
error: could not apply 9b2e43793326